### ISSUE TITLE
simplejson module not found

### ISSUE THREAD

**Issue by yaylinda** [YelpArchive/dataset-examples#19]
Hey, I came across your codebase, and I'm interested in using your json_to_csv_converter.py file to convert the .json files to .csv files from the yelp data challenge. However, when I try to run it, it can't locate where the simplejson module is. I was just wondering where that file was or how I could find it.

Thanks!

**Comment by Shobhit1** [comment]
Try installing the dependencies using 'pip install -e . 'and then run the python script again.

**Comment by patponseti** [comment]
I'm getting the same issue and knew that  the installation had gone wrong. This is going to be long but this is all of the issues I receive when I 'pip install -e .' Everything up to the point below runs smoothly until I hit this point. Any idea what's the issue?

"DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/req/req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/utils/**init**.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/9t/l6gc1kcn5872wnhxky33tcmh0000gn/T/pip-FkF1kE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'"

**Comment by patponseti** [comment]
Anyone have any idea on this?

**Comment by jiayuc** [comment]
I fixed it on line 10 using

```
#import simplejson as json
try:
    import simplejson as json
except ImportError:
    import json as json
```
